on:
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare release notes
        run: |
          sed -i -e 's/:ant:/\&#x1F41B;/g' \
          -e 's/:package:/\&#x1F4E6;/g' \
          -e 's/:telescope:/\&#x1F52D;/g' \
          -e 's/:broom:/\&#x1F9F9;/g' \
          -e 's/:memo:/\&#x1F4D2;/g' \
          release-notes.md
      - name: release notes content
        id: release-notes
        run: echo ::set-output name=content::$(cat release-notes.md)
      - name: send ms teams notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        env:
          INPUT_TITLE: "&#x1F4E2; Github Actions title"
          INPUT_TEXT: ${{ steps.release-notes.outputs.content }}
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          summary: "test from github actions"

