on:
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: send ms teams notification
        run: |
          content=$(sed -e 's/:ant:/\&#x1F41B;/g' \
                           -e 's/:package:/\&#x1F4E6;/g' \
                           -e 's/:telescope:/\&#x1F52D;/g' \
                           -e 's/:broom:/\&#x1F9F9;/g' \
                           -e 's/:memo:/\&#x1F4D2;/g' \
                           release-notes.md)
          payload="{
                    \"@context\": \"https://schema.org/extensions\",
                    \"@type\": \"MessageCard\",
                    \"title\": \"&#x1F4E2; Test Release\",
                    \"text\": \"${1}\",
                    \"potentialAction\": [
                      {
                        \"@type\": \"OpenUri\",
                        \"name\": \"Download Release Artifacts here\",
                        \"targets\": [
                          { \"os\": \"default\", \"uri\": \"https://github.com/uniqueck/github-actions-java-maven-test/releases/tag/latest\" }
                        ]
                      }
                    ]
                  }"
          curl --location --request POST ${{ secret.MS_TEAMS_WEBHOOK_URI }} \
                 --header 'Content-Type: application/json' \
                 --data-raw "${payload}"
