on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set tag as version
        run: mvn versions:set -DnewVersion=${GITHUB_REF##*/v} versions:commit
      - name: build release
        run: mvn --batch-mode verify
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: npm init release-it
        run: npm init release-it
      - name: npm install --save-dev @release-it/keep-a-changelog
        run: npm install --save-dev @release-it/keep-a-changelog
      - name: run release-it
        run: release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

