on: [push, workflow_dispatch]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          repo: rulebased-group/lfet-test-driver-maven-groovy
          workflow: "CI"