on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: cat ./.github/maven/settings.xml
        env:
          DEPLOY_USER: $GITHUB_ACTOR
          DEPLOY_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      - run: mvn -s ./.github/maven/settings.xml deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/$GITHUB_REPOSITORY
        env:
          DEPLOY_USER: $GITHUB_ACTOR
          DEPLOY_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
